using System.Reflection;
using System.Text;

namespace Dunet.Generator.UnionGeneration;

internal static class StringBuilderExtensions
{
    extension(StringBuilder self)
    {
        public StringBuilder AppendTypeParams(IReadOnlyList<TypeParameter> typeParams)
        {
            if (typeParams.Count <= 0)
            {
                return self;
            }

            var typeParamsCsv = string.Join(
                ", ",
                typeParams.Select(static typeParam => typeParam.Identifier)
            );

            return self.Append("<").Append(typeParamsCsv).Append(">");
        }

        /// <summary>
        /// Appends name of the given union, including each of its parent types separated by dots.
        /// </summary>
        /// <param name="builder">The string builder to append to.</param>
        /// <param name="union">The union to append the full name of.</param>
        public StringBuilder AppendFullUnionName(UnionDeclaration union)
        {
            var parentTypes = string.Join(".", union.ParentTypes);
            self.Append(parentTypes);

            if (union.ParentTypes.Count > 0)
            {
                self.Append(".");
            }

            return self.Append(union.Name);
        }

        public StringBuilder AppendAutoGeneratedCommentLine() =>
            self.AppendLine("// <auto-generated/>");

        /// <summary>
        /// Appends the GeneratedCodeAttribute, to better enable the code to be detected as generated.
        /// </summary>
        /// <param name="builder">The string builder to append to.</param>
        public StringBuilder AppendGeneratedCodeAttributeLine() =>
            self.AppendLine(
                $"""[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Dunet.Generator", "{GeneratorVersion}")]"""
            );

        public StringBuilder AppendPragmaWarningDisableCs1591Line() =>
            self.AppendLine("// Disable CS1591 - Missing XML comment on public member")
                .AppendLine("#pragma warning disable 1591");

        public StringBuilder AppendPragmaWarningRestoreCs1591Line() =>
            self.AppendLine("// Disable CS1591 - Missing XML comment on public member")
                .AppendLine("#pragma warning restore 1591");
    }

    private static string? GeneratorVersion { get; } = GetGeneratorVersion();

    private static string? GetGeneratorVersion()
    {
        var assembly = typeof(UnionGenerator).Assembly;
        var attribute = assembly.GetCustomAttribute<AssemblyInformationalVersionAttribute>();
        return attribute?.InformationalVersion;
    }
}
