using System.Text;
using Dunet.Generator.UnionGeneration;

namespace Dunet.Generator.UnionExtensionsGeneration;

internal static class UnionExtensionsSourceBuilder
{
    const string task = "System.Threading.Tasks.Task";
    const string valueTask = "System.Threading.Tasks.ValueTask";

    public static string GenerateExtensions(UnionDeclaration union)
    {
        if (union.Namespace is null)
        {
            throw new InvalidOperationException(
                "Cannot generate async match extensions if the union has no namespace."
            );
        }

        return new StringBuilder()
            .AppendAutoGeneratedCommentLine()
            .AppendPragmaWarningDisableCs1591Line()
            .AppendUsingStatements(union)
            .AppendLine()
            .AppendLine($"namespace {union.Namespace};")
            .AppendLine()
            .AppendGeneratedCodeAttributeLine()
            .AppendExtensionClassDeclaration(union)
            .AppendLine("{")
            .AppendMatchAsyncMethodForFuncs(union, task)
            .AppendMatchAsyncMethodForFuncs(union, valueTask)
            .AppendMatchAsyncMethodForActions(union, task)
            .AppendMatchAsyncMethodForActions(union, valueTask)
            .AppendSpecificMatchAsyncMethodForFuncs(union, task)
            .AppendSpecificMatchAsyncMethodForFuncs(union, valueTask)
            .AppendSpecificMatchAsyncMethodForActions(union, task)
            .AppendSpecificMatchAsyncMethodForActions(union, valueTask)
            .AppendLine("}")
            .AppendPragmaWarningRestoreCs1591Line()
            .ToString();
    }

    private static StringBuilder AppendExtensionClassDeclaration(
        this StringBuilder builder,
        UnionDeclaration union
    ) =>
        builder.AppendLine(
            $"{union.Accessibility.ToKeyword()} static class {union.Name}MatchExtensions"
        );

    private static StringBuilder AppendUsingStatements(
        this StringBuilder builder,
        UnionDeclaration union
    )
    {
        foreach (var import in union.Imports)
        {
            builder.AppendLine(import);
        }

        return builder;
    }

    private static StringBuilder AppendMatchAsyncMethodForFuncs(
        this StringBuilder builder,
        UnionDeclaration union,
        string taskType
    )
    {
        var methodTypeParams = union.TypeParameters.Prepend(new("TMatchOutput")).ToList();

        builder
            .Append($"    public static async {taskType}<TMatchOutput> MatchAsync")
            .AppendTypeParams(methodTypeParams)
            .AppendLine("(")
            .Append($"        this {taskType}<")
            .AppendFullUnionName(union)
            .AppendTypeParams(union.TypeParameters)
            .AppendLine("> unionTask,");

        for (int i = 0; i < union.Variants.Count; ++i)
        {
            var variant = union.Variants[i];

            builder
                .Append($"        System.Func<")
                .AppendFullUnionName(union)
                .AppendTypeParams(union.TypeParameters)
                .Append($".{variant.Identifier}")
                .Append($", TMatchOutput> {variant.Identifier.ToMethodParameterCase()}");

            if (i < union.Variants.Count - 1)
            {
                builder.Append(",");
            }

            builder.AppendLine();
        }

        builder.AppendLine($"    )");

        foreach (var typeParamConstraint in union.TypeParameterConstraints)
        {
            builder.AppendLine($"        {typeParamConstraint}");
        }

        builder.AppendLine($"    => (await unionTask.ConfigureAwait(false)).Match(");

        for (int i = 0; i < union.Variants.Count; ++i)
        {
            var variant = union.Variants[i];

            builder.Append($"            {variant.Identifier.ToMethodParameterCase()}");

            if (i < union.Variants.Count - 1)
            {
                builder.Append(",");
            }

            builder.AppendLine();
        }

        return builder.AppendLine("        );");
    }

    private static StringBuilder AppendMatchAsyncMethodForActions(
        this StringBuilder builder,
        UnionDeclaration union,
        string taskType
    )
    {
        builder
            .Append($"    public static async {taskType} MatchAsync")
            .AppendTypeParams(union.TypeParameters)
            .AppendLine("(")
            .Append($"        this {taskType}<")
            .AppendFullUnionName(union)
            .AppendTypeParams(union.TypeParameters)
            .AppendLine("> unionTask,");

        for (int i = 0; i < union.Variants.Count; ++i)
        {
            var variant = union.Variants[i];

            builder
                .Append($"        System.Action<")
                .AppendFullUnionName(union)
                .AppendTypeParams(union.TypeParameters)
                .Append($".{variant.Identifier}")
                .Append($"> {variant.Identifier.ToMethodParameterCase()}");

            if (i < union.Variants.Count - 1)
            {
                builder.Append(",");
            }

            builder.AppendLine();
        }

        builder.AppendLine($"    )");

        foreach (var typeParamConstraint in union.TypeParameterConstraints)
        {
            builder.AppendLine($"        {typeParamConstraint}");
        }

        builder.AppendLine($"    => (await unionTask.ConfigureAwait(false)).Match(");

        for (int i = 0; i < union.Variants.Count; ++i)
        {
            var variant = union.Variants[i];

            builder.Append($"            {variant.Identifier.ToMethodParameterCase()}");

            if (i < union.Variants.Count - 1)
            {
                builder.Append(",");
            }

            builder.AppendLine();
        }

        return builder.AppendLine("        );");
    }

    /// <summary>
    /// public static async TaskType<TMatchOuput> MatchSpecificAsync<T1, T2, ..., TMatchOutput>(
    ///     this Task<Parent1.Parent2.UnionType<T1, T2, ...>> unionTask,
    ///     System.Func<Parent1.Parent2.UnionType<T1, T2, ...>.Specific, TMatchOutput> @specific,
    ///     System.Func<TMatchOutput> @else
    /// )
    /// where T1 : notnull
    /// where T2 : notnull
    ///     =>
    ///         (await unionTask.ConfigureAwait(false))
    ///             .MatchSpecific(
    ///                 @specific,
    ///                 @else
    ///             );
    /// </summary>
    private static StringBuilder AppendSpecificMatchAsyncMethodForFuncs(
        this StringBuilder builder,
        UnionDeclaration union,
        string taskType
    )
    {
        foreach (var variant in union.Variants)
        {
            var methodTypeParams = union.TypeParameters.Append(new("TMatchOutput")).ToList();

            builder
                .Append(
                    $"    public static async {taskType}<TMatchOutput> Match{variant.Identifier}Async"
                )
                .AppendTypeParams(methodTypeParams)
                .AppendLine("(")
                .Append($"        this {taskType}<")
                .AppendFullUnionName(union)
                .AppendTypeParams(union.TypeParameters)
                .AppendLine("> unionTask,")
                .Append($"        System.Func<")
                .AppendFullUnionName(union)
                .AppendTypeParams(union.TypeParameters)
                .Append($".{variant.Identifier}")
                .AppendLine($", TMatchOutput> {variant.Identifier.ToMethodParameterCase()},")
                .AppendLine("        System.Func<TMatchOutput> @else")
                .AppendLine($"    )");

            foreach (var typeParamConstraint in union.TypeParameterConstraints)
            {
                builder.AppendLine($"    {typeParamConstraint}");
            }

            builder
                .AppendLine("        =>")
                .AppendLine($"            (await unionTask.ConfigureAwait(false))")
                .AppendLine($"                .Match{variant.Identifier}(")
                .AppendLine($"                    {variant.Identifier.ToMethodParameterCase()},")
                .AppendLine($"                    @else")
                .AppendLine("                );");
        }

        return builder;
    }

    /// <summary>
    /// public static async TaskType MatchSpecificAsync<T1, T2, ...>(
    ///     this Task<Parent1.Parent2.UnionType<T1, T2, ...>> unionTask,
    ///     System.Action<Parent1.Parent2.UnionType<T1, T2, ...>.Specific> @specific,
    ///     System.Action @else
    /// )
    /// where T1 : notnull
    /// where T2 : notnull
    ///     =>
    ///         (await unionTask.ConfigureAwait(false))
    ///             .MatchSpecific(
    ///                 @specific,
    ///                 @else
    ///             );
    /// </summary>
    private static StringBuilder AppendSpecificMatchAsyncMethodForActions(
        this StringBuilder builder,
        UnionDeclaration union,
        string taskType
    )
    {
        foreach (var variant in union.Variants)
        {
            builder
                .Append($"    public static async {taskType} Match{variant.Identifier}Async")
                .AppendTypeParams(union.TypeParameters)
                .AppendLine("(")
                .Append($"        this {taskType}<")
                .AppendFullUnionName(union)
                .AppendTypeParams(union.TypeParameters)
                .AppendLine("> unionTask,")
                .Append($"        System.Action<")
                .AppendFullUnionName(union)
                .AppendTypeParams(union.TypeParameters)
                .Append($".{variant.Identifier}")
                .AppendLine($"> {variant.Identifier.ToMethodParameterCase()},")
                .AppendLine("        System.Action @else")
                .AppendLine($"    )");

            foreach (var typeParamConstraint in union.TypeParameterConstraints)
            {
                builder.AppendLine($"    {typeParamConstraint}");
            }

            builder
                .AppendLine("        =>")
                .AppendLine($"            (await unionTask.ConfigureAwait(false))")
                .AppendLine($"                .Match{variant.Identifier}(")
                .AppendLine($"                    {variant.Identifier.ToMethodParameterCase()},")
                .AppendLine($"                    @else")
                .AppendLine("                );");
        }

        return builder;
    }
}
